<?php
return array(
    //节点配置
    'AutoNodesConf'=>array(
        //后台模块
        'Admin-后台模块'=>array(
            'User-用户管理'=>array(
                'users-用户列表',
                'add-添加',
                'edit-编辑',
                'delete-删除',
                'excel-导出',
                'editPersonalInfo-编辑个人信息',
            ),
            'Role-角色管理'=>array(
                'roles-角色列表',
                'add-添加',
                //'edit-编辑',
                'delete-删除',
                'assignnode-权限分配',
                'excel-导出',
            ),
            'Node-节点管理'=>array(
                'nodes-节点列表',
                'add-添加',
                'edit-编辑',
                'delete-删除',
            ),
            'Menu-菜单管理'=>array(
                'menus-菜单列表',
                'add-添加',
                'edit-编辑',
                'delete-删除',
            ),
        ),
        'Ling-测试模块'=>array(
            'Test-测试'=>array(
                'testOne-大小写测试1',
                'test_one-大小写测试2',
            ),
        ),
    ),
);